### ISSUE TITLE
[REQUEST] Pause game in background

### ISSUE THREAD

**Issue by SiTWulf** [ManlyMarco/SVS-HF_Patch#1]
Similar to Mute in background but pause the game.

**Comment by ManlyMarco** [comment]
F12 -> In BG

**Comment by SiTWulf** [comment]
@ManlyMarco 
I was referring to a plugin so that when it is in the background it pauses completely.
I remember in a previous game that there was a plugin so that when you put the game in the background it would stop completely, even releasing the temperature of the graphic card.

**Comment by ManlyMarco** [comment]
I see, so you want a full port of the GraphicsSettings plugin. The current IL2CPP version doesn't have this implemented unfortunately.
