### ISSUE TITLE
Can't install Summer Vacation HF Patch

### ISSUE THREAD

**Issue by TerminalHash** [ManlyMarco/SVS-HF_Patch#2]
throwing exception on this stage while trying install patch:
![ed](https://github.com/user-attachments/assets/c260e654-633b-4f91-81e0-1defa7f91611)

it's working only with NTFS partitions?
-- -- -- -- -- --
System info: Arch Linux x86_64, Linux 6.10.3-x64v-xanmod1-1
Wine version: wine-tkg-staging-fsync-git-9.19
Partition's filesystem is EXT4.

**Comment by ManlyMarco** [comment]
Filesystem shouldn't matter as long as the takeown and icacls exist and work as expected https://github.com/ManlyMarco/SVS-HF_Patch/blob/196c676393aedf302b342c5e1ea4d6084bf5b5c4/HelperLib/HelperLib.cs#L221

**Comment by TerminalHash** [comment]
okay, but how i can install this patch? without .NET Framework 4.7.2/4.8 installer doesnt run (instant crash with exception on start), with .NET Framework 3.5 same result as without 4.7.2/4.8. downgrading wine to Wine-GE 8.26 dont fixing this.

**Comment by TerminalHash** [comment]
im extracted via innoextract and just copied files into game directory, it's not good method, but i dont see another.
