### ISSUE TITLE
Il2CppSystem.IO.Compression.dll being reported as a Wacatac.B!ml. Probably a false positive, but wanted to ask just incase

### ISSUE THREAD

**Issue by ghost** [ManlyMarco/SVS-HF_Patch#3]
So after installing then launching for the first time, microsoft defender went off and deleted Il2CppSystem.IO.Compression.dll because it thought it was a Wacatac.B!ml Trojan. After flagging the file as safe and reverting it, I threw that file into VirusTotal, I got alerts only from Microsoft Defender and McAfee, so I assume it's a false positive, but wanted to ask just incase.

installation_folder\BepInEx\SamabakeScramble\interop\Il2CppSystem.IO.Compression.dll to be exact.
https://www.virustotal.com/gui/file/5472a3943c0312319941bbb0ff9b537e96f58bfd0bbbbbc6c33c7536faf892cb

**Comment by ManlyMarco** [comment]
It's not the first time it happens and definitely not the last, this is a common issue with the interop assemblies in all IL2CPP games. Some AVs see something in them that some malware somewhere used and call it bad anyways.
The best thing you can do is send the file to your AV vendor to verify as a false positive.

**Comment by ghost** [comment]
> It's not the first time it happens and definitely not the last, this is a common issue with the interop assemblies in all IL2CPP games. Some AVs see something in them that some malware somewhere used and call it bad anyways. The best thing you can do is send the file to your AV vendor to verify as a false positive.

Thanks for the explanation!
