### ISSUE TITLE
turn off translucent background effect in H scenes

### ISSUE THREAD

**Issue by ghost** [ManlyMarco/SVS-HF_Patch#4]
Hi, 

I'm not sure this is the best place to ask this question but I need some help. 

I remember when I played SVS months ago, there was an option to turn off the translucent background effect in H scenes so you can see other characters' reactions in the backgound. 

Somehow I'm having a hard time finding that plugin option after I reinstall the newer version of SVS and this patch recently. 

Do you have any idea where I can find that option/plugin?

Thanks

**Comment by ManlyMarco** [comment]
It's not a plugin option, it's part of the game, check game hotkeys page. Ask on discord server for general questions to get faster answers.

**Comment by ghost** [comment]
Thanks I figured it out. It's in the cheat tools F12.
